### ISSUE TITLE
Versioning and automated package deployment

### ISSUE THREAD

**Issue by brandonwillard** [RandallBalestriero/SymJAX#14]
Any preferences for a versioning system?  I've found [`versioneer`](https://github.com/warner/python-versioneer) pretty useful for this, so I can set it up if nothing else is preferred.

Also, what do you think about setting up a GitHub Action for package deployment?

**Comment by RandallBalestriero** [comment]
versioneer would work well indeed and yes good idea on setting up a GitHub Action !
