### ISSUE TITLE
theano.clone clone

### ISSUE THREAD

**Issue by twiecki** [RandallBalestriero/SymJAX#5]
This library looks super interesting. Do you plan to add a theano.clone-like functionality? That is very helpful and we for example use it in PyMC3 in critical parts.

**Comment by RandallBalestriero** [comment]
That is indeed a nice functionality that should be added in (probably this coming week) along this line there is also the nice ''givens'' argument of the theano.function that is really handy and will be added as well.

**Comment by RandallBalestriero** [comment]
Clone has been added (for now without all the Theano options)

https://symjax.readthedocs.io/en/latest/user/tutorial.html#clone-one-line-multipurpose-graph-replacement
