### ISSUE TITLE
General question

### ISSUE THREAD

**Issue by junpenglao** [RandallBalestriero/SymJAX#6]
Hi SymJAX devs:
I am a dev of [PyMC3](https://github.com/pymc-devs/pymc3/), which is a python library built on top of theano, so you might understand my excitement see this library. As the API is sufficiently similar to theano, we are very interested in trying out whether it would be a viable choice for us to switch the pymc3 backend. From a quick skim of the code, we have a few questions:

- General roadmap - what is your plan for the library? what problem you are trying to solve with it? We would like to know a bit more your priority in terms of adding feature and bug fix. For example, we would love that your library have a clone function like theano (https://github.com/RandallBalestriero/SymJAX/issues/5)
- We are a bit worry of the usage of global. For example, in https://github.com/RandallBalestriero/SymJAX/blob/master/symjax/base.py#L33 it seems to assume that only 1 graph is available in one user session (meaning they can only have one active model running). Moreover, the rng seed handling with global in (https://github.com/RandallBalestriero/SymJAX/blob/1cc1cbcdd15ec249d19d940a570b1d17e97a9c7a/symjax/base.py#L344) doesnt seems to be very safe. Since we are interested in probabilistic programming, reproducible random with stateless random Jax offer is a big feature we would like to get right, and migrating it to a stateful random using global doesnt feel very safe. Do you have some insight on why the current implementation is chosen?

cc @ferrine, @twiecki

**Comment by RandallBalestriero** [comment]
Hello ! 
Thank you for your interest in SymJAX.

- our plan is to greatly augment Jax with deep learning and IO functionalities to allow easy and rapid test of ideas for practitioners. Beyond that, our view is really to bring back something a la Theano but with augmented flexibility allowed by Jax. In particular, the idea of defining and tweaking first a computational graph which is then compiled and interfaced with the user. Nevertheless, we allow for on demand computation during the graph creation to let the user perform rapid tests/checks whenever needed.
- This is indeed a temporary (unsafe) set up that allows us to test the Jax random functionalities and experiment in our end-goal: providing both a numpy like (implicit Jax like) and a Jax like (explicit) handling of random ops as both have their advantages for different users.

Overall we are still in very early stages of the development where the library works and can already be used for practical applications but is not yet sound all around. We plan on releasing the first major stable version in less than a month which I think will be perfectly suited for your needs. Meanwhile we really appreciate any feedbacks/comments/contributions you might have.

**Comment by junpenglao** [comment]
That's great to hear! 

> Beyond that, our view is really to bring back something a la Theano but with augmented flexibility allowed by Jax. In particular, the idea of defining and tweaking first a computational graph which is then compiled and interfaced with the user. 

We agree with this 100%!

I am not sure what I could be help here, but I will start play with it and hopefully can provide some constructive feedback/contribution.

**Comment by RandallBalestriero** [comment]
That would be great, as you can attest many functionalities are still experimental; we are still working our way through finding the most efficient, user-friendly and natural way to design this library. Any feedback and suggestion is most welcome. As soon as the first stable version is released, contributions will be simpler and streamlined.

**Comment by junpenglao** [comment]
Sounds great! Also, if you would like to have a meeting together, we are eager to meet you and learn more it.

**Comment by RandallBalestriero** [comment]
That would be nice, please send me an email randallbalestriero@gmail.com so that we can coordinate that.
