### ISSUE TITLE
Variance Scaling Initializer

### ISSUE THREAD

**Issue by joaogui1** [RandallBalestriero/SymJAX#8]
What do you guys think of using Variance Scaling Initializer like tensorflow [does](https://www.tensorflow.org/api_docs/python/tf/keras/initializers/VarianceScaling), and then defining He, Glorot and LeCun initilizers using it? I would be happy to write the PR if you are interested in this idea

**Comment by RandallBalestriero** [comment]
This would indeed allow to streamline the definition of all those initializers. A PR would be welcome otherwise we can integrate that in the next few days.
